vim.keymap.set("n","<leader>gs", vim.cmd.Git)
vim.keymap.set("n","<leader>gd", vim.cmd.Gdiffsplit)
vim.keymap.set("n","<leader>gb", ":Git blame<CR>")
vim.keymap.set("n","<leader>gc", ":Git commit<CR>")
vim.keymap.set("n","<leader>gp", ":Git push<CR>")
vim.keymap.set("n","<leader>ga", ":Git add .<CR>")
