-- local ok, copilot = pcall(require, "copilot")
-- if not ok then
--     return
-- end
--
-- copilot.setup {
--     panel = {
--         enabled = true,
--         auto_refresh = false,
--         keymap = {
--             jump_next = "<c-j>",
--             jump_prev = "<c-k>",
--             accept = "<c-a>",
--             refresh = "r",
--             open = "<M-CR>",
--         },
--         layout = {
--             position = "bottom",
--             ratio = 0.4,
--         },
--     },
--     sugestion = {
--         enabled = true,
--         auto_trigger = false,
--         debounce = 75,
--         keymap = {
--             accept = "<c-a>",
--             accept_word = false,
--             accept_line = false,
--             next = "<c-j>",
--             prev = "<c-k>",
--             dismiss = "<C-e>",
--         },
--     },
-- }
